### ISSUE TITLE
Release of the network weights

### ISSUE THREAD

**Issue by RaphaelLorenzo** [LarsKreuzberg/4D-StOP#1]
Hello and thanks a lot for sharing your code !

Do you plan to share the network weights ? 

I tried training the network but I only have 8 GiB of GPU memory available, do you think there is a choice of parameter that would be suitable ? It tried reducing batch_num but it does not seems to be sufficient.

**Comment by LarsKreuzberg** [comment]
Hi!
Thanks for your request.
A 8GiB GPU is definitely too small for training. I used a 48GiB GPU for training. 
I plan to share a trained model for the 2-scan setup soon.

**Comment by topcomma** [comment]
Hi！
Thanks for your code.
I also can't not train the network on KITTI dataset with 12GiB GPU memory，which countered ‘out of memory'.
Could you share your pretrained network weight model？
Or share us the the ways of reducing the usage of GPU memory for the 4D StOP?

Thanks.

**Comment by LarsKreuzberg** [comment]
I have now shared a trained model. You can find the link in the readme in section Testing, Tracking and Evaluating.
