### ISSUE TITLE
Question regarding supplementary material

### ISSUE THREAD

**Issue by JulesSanchez** [LarsKreuzberg/4D-StOP#2]
In the supplementary material of the paper you compare the speed of 4D-PLS and 4D-StOP. You mention reporting the time in scan per second, but the legend of the graph is in seconds per scan ? Which is the correct one ?
I assume seconds per scan is the right one as 4 scans-based methods should be slower than 2 scans based methods. 
Does it mean 4-PLS and 4D-StOP would run at best at 0.35FPS in an online setting ?

**Comment by LarsKreuzberg** [comment]
Hi. Yes, seconds per scan is the correct one. Thanks for notifying.
